spring:
  application:
    name: db-comm-srv
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_db_password
    url: jdbc:mysql://127.0.0.1:3306/db_comm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

business:
  db:
    homePage:
      url: "https://www.douban.com"
      logout: "https://www.douban.com/accounts/logout?source=main&ck="
      login:
        url: "https://accounts.douban.com/j/mobile/login/basic"
        refer: "https://accounts.douban.com/passport/login?source=main"
        userAgent: "Mozilla/5.0"
        name: "your_phone"
        password: "your_password"
        remember: "false"
    group:
      comment: "up"
      commentUrl: "https://www.douban.com/group/topic/your_comment_page_id/add_comment#last"