spring:
  application:
    name: db-comm-srv
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_db_password
    url: jdbc:mysql://127.0.0.1:3306/db_comm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initial-size: 5
    max-active: 20
    min-idle: 5
    # 配置获取连接等待超时的时间
    max-wait: 3000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    filters: stat,wall,log4j2
server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

business:
  db:
    homePage:
      url: "https://www.douban.com"
      logout: "https://www.douban.com/accounts/logout?source=main&ck="
      login:
        url: "https://accounts.douban.com/j/mobile/login/basic"
        refer: "https://accounts.douban.com/passport/login?source=main"
        userAgent: "Mozilla/5.0"
        name: "your_phone"
        password: "your_password"
        remember: "false"
    group:
      comment: "up"
      commentUrl: "https://www.douban.com/group/topic/your_comment_page_id/add_comment#last"